### ISSUE TITLE
Error Two semicolon

### ISSUE THREAD

**Issue by mohamedo7x** [AbdulrahmanIsmailMohamed/Nodejs-E-Commerce-API#1]
https://github.com/AbdulrahmanIsmailMohamed/Nodejs-E-Commerce-API/blob/c9d4534f807bc615789c3f4833836bc83aad96cc/src/controllers/user.controller.js#LL25C15-L25C23

**Comment by AbdulrahmanIsmailMohamed** [comment]
Modified
